/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComeceAgoraRouteImport } from './routes/comece-agora'
import { Route as UnidadesSlugRouteImport } from './routes/unidades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeceAgoraRoute = ComeceAgoraRouteImport.update({
  id: '/comece-agora',
  path: '/comece-agora',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesSlugRoute = UnidadesSlugRouteImport.update({
  id: '/unidades/$slug',
  path: '/unidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comece-agora': typeof ComeceAgoraRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comece-agora': typeof ComeceAgoraRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comece-agora': typeof ComeceAgoraRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comece-agora' | '/unidades/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comece-agora' | '/unidades/$slug'
  id: '__root__' | '/' | '/comece-agora' | '/unidades/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComeceAgoraRoute: typeof ComeceAgoraRoute
  UnidadesSlugRoute: typeof UnidadesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comece-agora': {
      id: '/comece-agora'
      path: '/comece-agora'
      fullPath: '/comece-agora'
      preLoaderRoute: typeof ComeceAgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades/$slug': {
      id: '/unidades/$slug'
      path: '/unidades/$slug'
      fullPath: '/unidades/$slug'
      preLoaderRoute: typeof UnidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComeceAgoraRoute: ComeceAgoraRoute,
  UnidadesSlugRoute: UnidadesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
